# curl -u john:12345 http://localhost:8080/hello
GET http://localhost:8080/hello
Authorization: Basic john 12345

###

###

# curl -u jane:12345 http://localhost:8080/hello
GET http://localhost:8080/hello
Authorization: Basic jane 12345

###

